// Import semua icon yang digunakan dalam loop
const Qustions = {
  topAnswear: [
    {
      id: 1,
      question: "Apa yang saat ini Anda jual?",
      category: "Informasi Produk",
      options: [
        { text: "Produk", score: 4 },
        { text: "Jasa", score: 4 },
        { text: "Produk dan jasa", score: 2 },
        { text: "Belum punya produk atau jasa", score: 1 },
      ],
    },
    {
      id: 2,
      question: "Seberapa paham Anda dengan manfaat utama produk atau jasa Anda?",
      category: "Informasi Produk",
      options: [
        { text: "Sangat paham dan jelas", score: 4 },
        { text: "Cukup paham", score: 3 },
        { text: "Masih ragu-ragu", score: 2 },
        { text: "Tidak paham", score: 1 },
      ],
    },
    {
      id: 3,
      question: "Apakah Anda memiliki kompetitor dengan produk atau jasa yang mirip?",
      category: "Informasi Produk",
      options: [
        { text: "Ya, ada", score: 4 },
        { text: "Tidak ada", score: 2 },
        { text: "Ada, tapi tidak terlalu peduli", score: 1 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 4,
      question: "Apakah produk atau jasa Anda memiliki perbedaan dibandingkan kompetitor?",
      category: "Informasi Produk",
      options: [
        { text: "Ada perbedaan yang jelas", score: 4 },
        { text: "Tidak ada perbedaan", score: 1 },
        { text: "Belum yakin", score: 1 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 5,
      question: "Apakah Anda tahu siapa target utama pengguna produk atau jasa Anda?",
      category: "Target",
      options: [
        { text: "Tahu dengan jelas", score: 4 },
        { text: "Tahu secara umum", score: 3 },
        { text: "Masih ragu", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 6,
      question: "Berapa jumlah target pasar utama untuk satu brand Anda?",
      category: "Target",
      options: [
        { text: "Satu target pasar saja", score: 4 },
        { text: "Dua target pasar yang mirip", score: 2 },
        { text: "Dua target pasar dengan kriteria berbeda", score: 1 },
        { text: "Banyak dan beragam", score: 1 },
      ],
    },
    {
      id: 7,
      question: "Channel online mana yang paling banyak menghasilkan penjualan saat ini?",
      category: "Target",
      options: [
        { text: "Landing page / website", score: 4 },
        { text: "Marketplace (Tokopedia, Shopee, Lazada)", score: 4 },
        { text: "Media sosial (Instagram, Facebook, TikTok, WhatsApp)", score: 4 },
        { text: "Belum pernah dicek", score: 1 },
      ],
    },
    {
      id: 8,
      question: "Menurut Anda, apa alasan utama orang membeli produk Anda?",
      category: "Target",
      options: [
        { text: "Karena kualitasnya bagus", score: 4 },
        { text: "Karena harganya murah", score: 2 },
        { text: "Karena promo atau diskon", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 9,
      question: "Bagaimana posisi harga produk Anda dibandingkan kompetitor?",
      category: "Harga",
      options: [
        { text: "Lebih murah", score: 4 },
        { text: "Lebih mahal", score: 4 },
        { text: "Sama saja", score: 4 },
        { text: "Tidak tahu harga kompetitor", score: 1 },
      ],
    },
    {
      id: 10,
      question: "Apa yang biasanya Anda lakukan jika kompetitor menjual lebih murah?",
      category: "Harga",
      options: [
        { text: "Mempertahankan harga dan mengedukasi kualitas", score: 4 },
        { text: "Menurunkan harga", score: 2 },
        { text: "Mengganti produk", score: 2 },
        { text: "Tidak melakukan apa-apa", score: 1 },
      ],
    },
    {
      id: 11,
      question: "Apa yang Anda lakukan jika harga kompetitor lebih mahal dari produk Anda?",
      category: "Harga",
      options: [
        { text: "Mempertahankan harga dan promosi", score: 4 },
        { text: "Mempertahankan harga", score: 3 },
        { text: "Ikut menaikkan harga supaya lebih untung", score: 2 },
        { text: "Tidak melakukan apa-apa", score: 1 },
      ],
    },
    {
      id: 12,
      question: "Apa pertimbangan utama Anda dalam menentukan harga produk?",
      category: "Harga",
      options: [
        { text: "Agar menarik banyak pembeli dengan harga terjangkau", score: 4 },
        { text: "Agar produk dianggap berkualitas bagus dengan harga mahal", score: 4 },
        { text: "Agar kompetitif dengan harga kompetitor", score: 3 },
        { text: "Yang penting dapat untung", score: 1 },
      ],
    },
    {
      id: 13,
      question: "Seberapa sering calon pembeli baru menanyakan hal yang sama seperti pembeli sebelumnya?",
      category: "Cara Menjual",
      options: [
        { text: "Jarang bertanya dan terjadi penjualan", score: 4 },
        { text: "Sering bertanya dan terjadi penjualan", score: 3 },
        { text: "Jarang bertanya tapi tidak ada penjualan", score: 2 },
        { text: "Sering bertanya tapi tidak ada penjualan", score: 1 },
      ],
    },
    {
      id: 14,
      question: "Apakah Anda sudah memiliki alur penjualan?",
      category: "Cara Menjual",
      options: [
        { text: "Sudah punya", score: 4 },
        { text: "Ingin membuat", score: 2 },
        { text: "Belum punya", score: 1 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 15,
      question: "Apa yang biasanya Anda lakukan saat pertama kali bertemu calon pembeli?",
      category: "Cara Menjual",
      options: [
        { text: "Mencari tahu atau menanyakan kebutuhan calon pembeli", score: 4 },
        { text: "Langsung menawarkan produk", score: 2 },
        { text: "Menawarkan promo atau diskon", score: 2 },
        { text: "Bingung harus melakukan apa", score: 1 },
      ],
    },
    {
      id: 16,
      question: "Apa yang biasanya Anda lakukan ketika penjualan menurun?",
      category: "Cara Menjual",
      options: [
        { text: "Mengevaluasi cara menjual", score: 4 },
        { text: "Mengevaluasi produk", score: 4 },
        { text: "Menurunkan harga", score: 2 },
        { text: "Menunggu saja", score: 1 },
      ],
    },
    {
      id: 17,
      question: "Bagaimana perasaan Anda saat melihat laporan penjualan 3 bulan terakhir?",
      category: "Reflektif",
      options: [
        { text: "Senang", score: 4 },
        { text: "Biasa saja", score: 3 },
        { text: "Cemas", score: 2 },
        { text: "Tidak pernah melihat laporan", score: 1 },
      ],
    },
    {
      id: 18,
      question: "Apa tantangan terbesar dalam penjualan Anda saat ini?",
      category: "Reflektif",
      options: [
        { text: "Tidak ada", score: 4 },
        { text: "Produk belum dikenal dengan baik", score: 3 },
        { text: "Harga terasa lebih mahal", score: 3 },
        { text: "Belum tahu target pembeli yang tepat", score: 3 },
      ],
    },
    {
      id: 19,
      question: "Menurut Anda, apakah produk Anda sudah bagus?",
      category: "Reflektif",
      options: [
        { text: "Ya, sudah bagus", score: 4 },
        { text: "Belum bagus", score: 2 },
        { text: "Masih ragu", score: 2 },
        { text: "Tidak tahu standar penilaiannya", score: 1 },
      ],
    },
    {
      id: 20,
      question: "Apakah brand Anda sudah memiliki logo?",
      category: "Identitas Visual",
      options: [
        { text: "Sudah", score: 4 },
        { text: "Baru berencana membuat", score: 3 },
        { text: "Belum", score: 2 },
        { text: "Tidak merasa butuh logo", score: 1 },
      ],
    },
    {
      id: 21,
      question: "Bagaimana karakter tampilan logo brand Anda?",
      category: "Identitas Visual",
      options: [
        { text: "Sederhana", score: 4 },
        { text: "Berwarna-warni", score: 3 },
        { text: "Banyak detail / terlihat ramai", score: 2 },
        { text: "Belum punya logo", score: 1 },
      ],
    },
    {
      id: 22,
      question: "Apakah brand Anda memiliki banyak logo?",
      category: "Identitas Visual",
      options: [
        { text: "Hanya satu", score: 4 },
        { text: "Ada beberapa", score: 2 },
        { text: "Ya, banyak", score: 1 },
        { text: "Belum punya logo", score: 1 },
      ],
    },
    {
      id: 23,
      question: "Apakah brand Anda memiliki warna khas?",
      category: "Identitas Visual",
      options: [
        { text: "Ada satu warna khas", score: 4 },
        { text: "Tidak ada warna khas", score: 1 },
        { text: "Menggunakan banyak warna bergantian", score: 1 },
        { text: "Belum pernah memikirkan warna brand", score: 1 },
      ],
    },
    {
      id: 24,
      question: "Apakah warna brand selalu digunakan dalam konten promosi?",
      category: "Identitas Visual",
      options: [
        { text: "Selalu digunakan", score: 4 },
        { text: "Kadang-kadang", score: 3 },
        { text: "Tidak pernah", score: 2 },
        { text: "Tidak punya warna khusus", score: 1 },
      ],
    },
  ],
  badAnswear: [
    {
      id: 1,
      question: "Apa yang saat ini Anda jual?",
      category: "Informasi Produk",
      options: [
        { text: "Produk", score: 1 },
        { text: "Jasa", score: 2 },
        { text: "Produk dan jasa", score: 3 },
        { text: "Belum punya produk atau jasa", score: 4 },
      ],
    },
    {
      id: 2,
      question: "Seberapa paham Anda dengan manfaat utama produk atau jasa Anda?",
      category: "Informasi Produk",
      options: [
        { text: "Sangat paham dan jelas", score: 4 },
        { text: "Cukup paham", score: 3 },
        { text: "Masih ragu-ragu", score: 2 },
        { text: "Tidak paham", score: 1 },
      ],
    },
    {
      id: 3,
      question: "Apakah Anda memiliki kompetitor dengan produk atau jasa yang mirip?",
      category: "Informasi Produk",
      options: [
        { text: "Ya, ada", score: 4 },
        { text: "Tidak ada", score: 3 },
        { text: "Ada, tapi tidak terlalu peduli", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 4,
      question: "Apakah produk atau jasa Anda memiliki perbedaan dibandingkan kompetitor?",
      category: "Informasi Produk",
      options: [
        { text: "Ada perbedaan yang jelas", score: 4 },
        { text: "Tidak ada perbedaan", score: 3 },
        { text: "Belum yakin", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 5,
      question: "Apakah Anda tahu siapa target utama pengguna produk atau jasa Anda?",
      category: "Target",
      options: [
        { text: "Tahu dengan jelas", score: 4 },
        { text: "Tahu secara umum", score: 3 },
        { text: "Masih ragu", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 6,
      question: "Berapa jumlah target pasar utama untuk satu brand Anda?",
      category: "Target",
      options: [
        { text: "Satu target pasar saja", score: 4 },
        { text: "Dua target pasar yang mirip", score: 3 },
        { text: "Dua target pasar dengan kriteria berbeda", score: 2 },
        { text: "Banyak dan Beragam", score: 1 },
      ],
    },
    {
      id: 7,
      question: "Channel online mana yang paling banyak menghasilkan penjualan saat ini?",
      category: "Target",
      options: [
        { text: "Landing page / website", score: 4 },
        { text: "Marketplace (Tokopedia, Shopee, Lazada)", score: 3 },
        { text: "Media sosial (Instagram, Facebook, TikTok, WhatsApp)", score: 2 },
        { text: "Belum pernah dicek", score: 1 },
      ],
    },
    {
      id: 8,
      question: "Menurut Anda, apa alasan utama orang membeli produk Anda?",
      category: "Target",
      options: [
        { text: "Karena harganya murah", score: 2 },
        { text: "Karena kualitasnya bagus", score: 4 },
        { text: "Tidak tahu", score: 3 },
        { text: "Karena promo atau diskon", score: 1 },
      ],
    },
    {
      id: 9,
      question: "Bagaimana posisi harga produk Anda dibandingkan kompetitor?",
      category: "Harga",
      options: [
        { text: "Lebih murah", score: 4 },
        { text: "Lebih mahal", score: 3 },
        { text: "Sama saja", score: 2 },
        { text: "Tidak tahu harga kompetitor", score: 1 },
      ],
    },
    {
      id: 10,
      question: "Apa yang biasanya Anda lakukan jika kompetitor menjual lebih murah?",
      category: "Harga",
      options: [
        { text: "Menurunkan harga", score: 2 },
        { text: "Mempertahankan harga dan mengedukasi kualitas", score: 4 },
        { text: "Mengganti produk", score: 3 },
        { text: "Tidak melakukan apa-apa", score: 1 },
      ],
    },
    {
      id: 11,
      question: "Apa yang Anda lakukan jika harga kompetitor lebih mahal dari produk Anda?",
      category: "Harga",
      options: [
        { text: "Ikut menaikkan harga supaya lebih untung", score: 2 },
        { text: "Mempertahankan harga", score: 3 },
        { text: "Mempertahankan harga dan promosi", score: 4 },
        { text: "Tidak melakukan apa-apa", score: 1 },
      ],
    },
    {
      id: 12,
      question: "Apa pertimbangan utama Anda dalam menentukan harga produk?",
      category: "Harga",
      options: [
        { text: "Agar menarik banyak pembeli dengan harga terjangkau", score: 4 },
        { text: "Agar produk dianggap berkualitas bagus dengan harga mahal", score: 3 },
        { text: "Agar kompetitif dengan harga kompetitor", score: 2 },
        { text: "Yang penting dapat untung", score: 1 },
      ],
    },
    {
      id: 13,
      question: "Seberapa sering calon pembeli baru menanyakan hal yang sama seperti pembeli sebelumnya?",
      category: "Cara Menjual",
      options: [
        { text: "Jarang bertanya dan terjadi penjualan", score: 4 },
        { text: "Jarang bertanya tapi tidak ada penjualan", score: 3 },
        { text: "Sering bertanya dan terjadi penjualan", score: 2 },
        { text: "Sering bertanya tapi tidak ada penjualan", score: 1 },
      ],
    },
    {
      id: 14,
      question: "Apakah Anda sudah memiliki alur penjualan?",
      category: "Cara Menjual",
      options: [
        { text: "Sudah punya", score: 4 },
        { text: "Belum punya", score: 3 },
        { text: "Ingin membuat", score: 2 },
        { text: "Tidak tahu", score: 1 },
      ],
    },
    {
      id: 15,
      question: "Apa yang biasanya Anda lakukan saat pertama kali bertemu calon pembeli?",
      category: "Cara Menjual",
      options: [
        { text: "Langsung menawarkan produk", score: 2 },
        { text: "Mencari tahu atau menanyakan kebutuhan calon pembeli", score: 4 },
        { text: "Menawarkan promo atau diskon", score: 3 },
        { text: "Bingung harus melakukan apa", score: 1 },
      ],
    },
    {
      id: 16,
      question: "Apa yang biasanya Anda lakukan ketika penjualan menurun?",
      category: "Cara Menjual",
      options: [
        { text: "Mengevaluasi cara menjual", score: 4 },
        { text: "Mengevaluasi produk", score: 3 },
        { text: "Menurunkan harga", score: 2 },
        { text: "Menunggu saja", score: 1 },
      ],
    },
    {
      id: 17,
      question: "Bagaimana perasaan Anda saat melihat laporan penjualan 3 bulan terakhir?",
      category: "Reflektif",
      options: [
        { text: "Senang", score: 4 },
        { text: "Cemas", score: 3 },
        { text: "Biasa saja", score: 2 },
        { text: "Tidak pernah melihat laporan", score: 1 },
      ],
    },
    {
      id: 18,
      question: "Apa tantangan terbesar dalam penjualan Anda saat ini?",
      category: "Reflektif",
      options: [
        { text: "Produk belum dikenal dengan baik", score: 3 },
        { text: "Harga terasa lebih mahal", score: 2 },
        { text: "Belum tahu target pembeli yang tepat", score: 1 },
        { text: "Tidak ada", score: 4 },
      ],
    },
    {
      id: 19,
      question: "Menurut Anda, apakah produk Anda sudah bagus?",
      category: "Reflektif",
      options: [
        { text: "Ya, sudah bagus", score: 4 },
        { text: "Belum bagus", score: 3 },
        { text: "Masih ragu", score: 2 },
        { text: "Tidak tahu standar penilaiannya", score: 1 },
      ],
    },
    {
      id: 20,
      question: "Apakah brand Anda sudah memiliki logo?",
      category: "Identitas Visual",
      options: [
        { text: "Sudah", score: 4 },
        { text: "Belum", score: 3 },
        { text: "Baru berencana membuat", score: 2 },
        { text: "Tidak merasa butuh logo", score: 1 },
      ],
    },
    {
      id: 21,
      question: "Bagaimana karakter tampilan logo brand Anda?",
      category: "Identitas Visual",
      options: [
        { text: "Sederhana", score: 4 },
        { text: "Berwarna-warni", score: 2 },
        { text: "Banyak detail / terlihat ramai", score: 1 },
        { text: "Belum punya logo", score: 1 },
      ],
    },
    {
      id: 22,
      question: "Apakah brand Anda memiliki banyak logo?",
      category: "Identitas Visual",
      options: [
        { text: "Ya, banyak", score: 1 },
        { text: "Ada beberapa", score: 3 },
        { text: "Hanya satu", score: 4 },
        { text: "Belum punya logo", score: 1 },
      ],
    },
    {
      id: 23,
      question: "Apakah brand Anda memiliki warna khas?",
      category: "Identitas Visual",
      options: [
        { text: "Ada satu warna khas", score: 4 },
        { text: "Tidak ada warna khas", score: 3 },
        { text: "Menggunakan banyak warna bergantian", score: 2 },
        { text: "Belum pernah memikirkan warna brand", score: 1 },
      ],
    },
    {
      id: 24,
      question: "Apakah warna brand selalu digunakan dalam konten promosi?",
      category: "Identitas Visual",
      options: [
        { text: "Selalu digunakan", score: 4 },
        { text: "Kadang-kadang", score: 2 },
        { text: "Tidak pernah", score: 3 },
        { text: "Tidak punya warna khusus", score: 4 },
      ],
    },
  ],
  randomAnswear: [
    {
      id: 1,
      question: "Apa yang saat ini Anda jual?",
      category: "Informasi Produk",
      options: [
        { text: "Produk", score: 4 },
        { text: "Jasa", score: 2 },
        { text: "Produk dan jasa", score: 1 },
        { text: "Belum punya produk atau jasa", score: 3 },
      ],
    },
    {
      id: 2,
      question: "Seberapa paham Anda dengan manfaat utama produk atau jasa Anda?",
      category: "Informasi Produk",
      options: [
        { text: "Sangat paham dan jelas", score: 2 },
        { text: "Cukup paham", score: 4 },
        { text: "Masih ragu-ragu", score: 1 },
        { text: "Tidak paham", score: 3 },
      ],
    },
    {
      id: 3,
      question: "Apakah Anda memiliki kompetitor dengan produk atau jasa yang mirip?",
      category: "Informasi Produk",
      options: [
        { text: "Ya, ada", score: 1 },
        { text: "Tidak ada", score: 4 },
        { text: "Ada, tapi tidak terlalu peduli", score: 3 },
        { text: "Tidak tahu", score: 2 },
      ],
    },
    {
      id: 4,
      question: "Apakah produk atau jasa Anda memiliki perbedaan dibandingkan kompetitor?",
      category: "Informasi Produk",
      options: [
        { text: "Ada perbedaan yang jelas", score: 3 },
        { text: "Tidak ada perbedaan", score: 1 },
        { text: "Belum yakin", score: 4 },
        { text: "Tidak tahu", score: 2 },
      ],
    },
    {
      id: 5,
      question: "Apakah Anda tahu siapa target utama pengguna produk atau jasa Anda?",
      category: "Target",
      options: [
        { text: "Tahu dengan jelas", score: 2 },
        { text: "Tahu secara umum", score: 1 },
        { text: "Masih ragu", score: 4 },
        { text: "Tidak tahu", score: 3 },
      ],
    },
    {
      id: 6,
      question: "Berapa jumlah target pasar utama untuk satu brand Anda?",
      category: "Target",
      options: [
        { text: "Satu target pasar saja", score: 3 },
        { text: "Dua target pasar yang mirip", score: 1 },
        { text: "Dua target pasar dengan kriteria berbeda", score: 4 },
        { text: "Banyak dan Beragam", score: 2 },
      ],
    },
    {
      id: 7,
      question: "Channel online mana yang paling banyak menghasilkan penjualan saat ini?",
      category: "Target",
      options: [
        { text: "Landing page / website", score: 1 },
        { text: "Marketplace (Tokopedia, Shopee, Lazada)", score: 2 },
        { text: "Media sosial (Instagram, Facebook, TikTok, WhatsApp)", score: 4 },
        { text: "Belum pernah dicek", score: 3 },
      ],
    },
    {
      id: 8,
      question: "Menurut Anda, apa alasan utama orang membeli produk Anda?",
      category: "Target",
      options: [
        { text: "Karena harganya murah", score: 3 },
        { text: "Karena kualitasnya bagus", score: 1 },
        { text: "Tidak tahu", score: 4 },
        { text: "Karena promo atau diskon", score: 2 },
      ],
    },
    {
      id: 9,
      question: "Bagaimana posisi harga produk Anda dibandingkan kompetitor?",
      category: "Harga",
      options: [
        { text: "Lebih murah", score: 2 },
        { text: "Lebih mahal", score: 1 },
        { text: "Sama saja", score: 4 },
        { text: "Tidak tahu harga kompetitor", score: 3 },
      ],
    },
    {
      id: 10,
      question: "Apa yang biasanya Anda lakukan jika kompetitor menjual lebih murah?",
      category: "Harga",
      options: [
        { text: "Menurunkan harga", score: 4 },
        { text: "Mempertahankan harga dan mengedukasi kualitas", score: 1 },
        { text: "Mengganti produk", score: 2 },
        { text: "Tidak melakukan apa-apa", score: 3 },
      ],
    },
    {
      id: 11,
      question: "Apa yang Anda lakukan jika harga kompetitor lebih mahal dari produk Anda?",
      category: "Harga",
      options: [
        { text: "Ikut menaikkan harga supaya lebih untung", score: 3 },
        { text: "Mempertahankan harga", score: 2 },
        { text: "Mempertahankan harga dan promosi", score: 1 },
        { text: "Tidak melakukan apa-apa", score: 4 },
      ],
    },
    {
      id: 12,
      question: "Apa pertimbangan utama Anda dalam menentukan harga produk?",
      category: "Harga",
      options: [
        { text: "Agar menarik banyak pembeli dengan harga terjangkau", score: 2 },
        { text: "Agar produk dianggap berkualitas bagus dengan harga mahal", score: 1 },
        { text: "Agar kompetitif dengan harga kompetitor", score: 4 },
        { text: "Yang penting dapat untung", score: 3 },
      ],
    },
    {
      id: 13,
      question: "Seberapa sering calon pembeli baru menanyakan hal yang sama seperti pembeli sebelumnya?",
      category: "Cara Menjual",
      options: [
        { text: "Jarang bertanya dan terjadi penjualan", score: 3 },
        { text: "Jarang bertanya tapi tidak ada penjualan", score: 1 },
        { text: "Sering bertanya dan terjadi penjualan", score: 4 },
        { text: "Sering bertanya tapi tidak ada penjualan", score: 2 },
      ],
    },
    {
      id: 14,
      question: "Apakah Anda sudah memiliki alur penjualan?",
      category: "Cara Menjual",
      options: [
        { text: "Sudah punya", score: 2 },
        { text: "Belum punya", score: 4 },
        { text: "Ingin membuat", score: 1 },
        { text: "Tidak tahu", score: 3 },
      ],
    },
    {
      id: 15,
      question: "Apa yang biasanya Anda lakukan saat pertama kali bertemu calon pembeli?",
      category: "Cara Menjual",
      options: [
        { text: "Langsung menawarkan produk", score: 1 },
        { text: "Mencari tahu atau menanyakan kebutuhan calon pembeli", score: 3 },
        { text: "Menawarkan promo atau diskon", score: 4 },
        { text: "Bingung harus melakukan apa", score: 2 },
      ],
    },
    {
      id: 16,
      question: "Apa yang biasanya Anda lakukan ketika penjualan menurun?",
      category: "Cara Menjual",
      options: [
        { text: "Mengevaluasi cara menjual", score: 4 },
        { text: "Mengevaluasi produk", score: 2 },
        { text: "Menurunkan harga", score: 1 },
        { text: "Menunggu saja", score: 3 },
      ],
    },
    {
      id: 17,
      question: "Bagaimana perasaan Anda saat melihat laporan penjualan 3 bulan terakhir?",
      category: "Reflektif",
      options: [
        { text: "Senang", score: 1 },
        { text: "Cemas", score: 4 },
        { text: "Biasa saja", score: 3 },
        { text: "Tidak pernah melihat laporan", score: 2 },
      ],
    },
    {
      id: 18,
      question: "Apa tantangan terbesar dalam penjualan Anda saat ini?",
      category: "Reflektif",
      options: [
        { text: "Produk belum dikenal dengan baik", score: 2 },
        { text: "Harga terasa lebih mahal", score: 4 },
        { text: "Belum tahu target pembeli yang tepat", score: 3 },
        { text: "Tidak ada", score: 1 },
      ],
    },
    {
      id: 19,
      question: "Menurut Anda, apakah produk Anda sudah bagus?",
      category: "Reflektif",
      options: [
        { text: "Ya, sudah bagus", score: 3 },
        { text: "Belum bagus", score: 1 },
        { text: "Masih ragu", score: 4 },
        { text: "Tidak tahu standar penilaiannya", score: 2 },
      ],
    },
    {
      id: 20,
      question: "Apakah brand Anda sudah memiliki logo?",
      category: "Identitas Visual",
      options: [
        { text: "Sudah", score: 4 },
        { text: "Belum", score: 1 },
        { text: "Baru berencana membuat", score: 3 },
        { text: "Tidak merasa butuh logo", score: 2 },
      ],
    },
    {
      id: 21,
      question: "Bagaimana karakter tampilan logo brand Anda?",
      category: "Identitas Visual",
      options: [
        { text: "Sederhana", score: 2 },
        { text: "Berwarna-warni", score: 4 },
        { text: "Banyak detail / terlihat ramai", score: 3 },
        { text: "Belum punya logo", score: 1 },
      ],
    },
    {
      id: 22,
      question: "Apakah brand Anda memiliki banyak logo?",
      category: "Identitas Visual",
      options: [
        { text: "Ya, banyak", score: 4 },
        { text: "Ada beberapa", score: 2 },
        { text: "Hanya satu", score: 1 },
        { text: "Belum punya logo", score: 3 },
      ],
    },
    {
      id: 23,
      question: "Apakah brand Anda memiliki warna khas?",
      category: "Identitas Visual",
      options: [
        { text: "Ada satu warna khas", score: 1 },
        { text: "Tidak ada warna khas", score: 4 },
        { text: "Menggunakan banyak warna bergantian", score: 2 },
        { text: "Belum pernah memikirkan warna brand", score: 3 },
      ],
    },
    {
      id: 24,
      question: "Apakah warna brand selalu digunakan dalam konten promosi?",
      category: "Identitas Visual",
      options: [
        { text: "Selalu digunakan", score: 3 },
        { text: "Kadang-kadang", score: 1 },
        { text: "Tidak pernah", score: 4 },
        { text: "Tidak punya warna khusus", score: 2 },
      ],
    },
  ],
};

export default Qustions;
